### ISSUE TITLE
Use of uninitialized value in die at BeanCounter.pm line 144.

### ISSUE THREAD

**Issue by anoduck** [eddelbuettel/beancounter#3]
Since making the transition from Linux to OpenBSD I have not been successful at setting up beancounter. I know this is rock solid code, but for some reason regardless of which database I use, I get the same error. 

```
Use of uninitialized value in die at /usr/local/libdata/perl5/site_perl/Finance/BeanCounter.pm line 144.                                                    
Died at /usr/local/libdata/perl5/site_perl/Finance/BeanCounter.pm line 144.
```

The section that contains line 144, is part of beancounter's database test to see if the database is configured correctly. The line of code does not look like one I can just comment out something, and go on my way. I am not sure why my system is not defining that particular variable. 

The block of code in question is:

```
sub TestInsufficientDatabaseSchema($$) {
  my ($dbh, $required) = @_;
  my @tables = $dbh->tables();
  die "Database does not contain table beancounter. " .
    "Please run 'update_beancounter'.\n" unless grep /beancounter/, @tables;
  my $sql = q{select version from beancounter};
  my @res = $dbh->selectrow_array($sql) or die $dbh->errstr;
  my $dbschema = $res[0];
  my $num_required = ConvertVersionToLargeInteger($required);
  my $num_schema = ConvertVersionToLargeInteger($dbschema);
  print "Database has schema $dbschema, we require version $required\n"
    if $Config{debug};
  return ($num_schema < $num_required); # extensive testing was required =:-)
}
```

What am I doing wrong?

**Comment by eddelbuettel** [comment]
BeanCounter is in a funk anyway as the Yahoo! data source we relied upon for 20 years is no more. I still use it, but do the daily inject of new data outside of it.

The line here appears to be

```perl
my @res = $dbh->selectrow_array($sql) or die $dbh->errstr;   
```

I would debug this locally -- can you retrieve the version of the schema or not? -- and adjust accordingly.  I don't have access to a BSD system, and I don't really program in Perl anymore either...
